/*
 * OpenAPI Movielist
 *
 * This is a sample server Movie list server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	MovieApiService := openapi.NewMovieApiService()
	MovieApiController := openapi.NewMovieApiController(MovieApiService)

	router := openapi.NewRouter(MovieApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
