/*
 * OpenAPI Movielist
 *
 * This is a sample server Movie list server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MovieApiService is a service that implents the logic for the MovieApiServicer
// This service should implement the business logic for every endpoint for the MovieApi API.
// Include any external packages or services that will be required by this service.
type MovieApiService struct {
}

// NewMovieApiService creates a default api service
func NewMovieApiService() MovieApiServicer {
	return &MovieApiService{}
}

// GetMovieById - Find movie by ID
func (s *MovieApiService) GetMovieById(movieId int64) (interface{}, error) {
	// Add api_movie_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return GetMovie(movieId)
}

// ListMovies - List Movies
func (s *MovieApiService) ListMovies() (interface{}, error) {
	// Add api_movie_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return GetMovies()
}
